#!/bin/bash
source $(dirname $0)/.private

APP_NAME="mock-api-service"
IMAGE_NAME="mock-api-service"
MONGO_URI=$(use "mongo_uri")
JWT_SECRET=$(use "jwt_secret")

heroku container:login

heroku config:set MONGO_COLLECTION_NAME=setting --app ${APP_NAME}
heroku config:set MONGO_DATABASE_NAME=mock-api-service --app ${APP_NAME}
heroku config:set MONGO_URI=${MONGO_URI} --app ${APP_NAME}
heroku config:set JWT_SECRET=${JWT_SECRET} --app ${APP_NAME}

heroku container:push web --app ${APP_NAME}
heroku container:release web --app ${APP_NAME}
