#!/bin/bash

IMAGE_NAME="mock-api-service"

docker network create -d bridge ms_net
docker run -d --name mongodb --network ms_net -p 27017:27017 -v mongodb_data:/data/db --restart always -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password mongo

docker stop ${IMAGE_NAME} 2>&1>/dev/null
docker rm ${IMAGE_NAME} 2>&1>/dev/null
docker rmi ${IMAGE_NAME} 2>&1>/dev/null

docker build -t ${IMAGE_NAME} .
docker run --name ${IMAGE_NAME} --network ms_net -p 8080:8080 -d ${IMAGE_NAME}

